window.routes = [
  {"from": "JFK", "to": "LAX", "co2": 500},
  {"from": "JFK", "to": "ORD", "co2": 200},
  {"from": "JFK", "to": "ATL", "co2": 250},
  {"from": "JFK", "to": "SFO", "co2": 550},
  {"from": "ORD", "to": "LAX", "co2": 300},
  {"from": "ORD", "to": "DFW", "co2": 180},
  {"from": "ATL", "to": "LAX", "co2": 400},
  {"from": "ATL", "to": "DFW", "co2": 150},
  {"from": "DFW", "to": "LAX", "co2": 200},
  {"from": "DFW", "to": "SFO", "co2": 250},
  {"from": "SFO", "to": "LAX", "co2": 100},
  {"from": "SFO", "to": "SEA", "co2": 120},
  {"from": "SEA", "to": "LAX", "co2": 200},
  {"from": "ABE", "to": "DFW", "co2": 430},
  {"from": "ABE", "to": "ATL", "co2": 210},
  {"from": "ABE", "to": "ORD", "co2": 220},
  {"from": "ABE", "to": "JFK", "co2": 340},
  {"from": "DFW", "to": "JFK", "co2": 320}
]
